// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GradeManagementApp_Back.Models;

public partial class Class
{
    public int Id { get; set; }

    public int GradeId { get; set; }

    public string Naziv { get; set; }

    public bool KombinovanoOdeljenje { get; set; }

    public int VrstaOdeljenjaId { get; set; }

    public bool CelodnevnaNastava { get; set; }

    public bool IzdvojenoOdeljenje { get; set; }

    public string NazivIzdvojeneSkole { get; set; }

    public string OdeljenskiStaresina { get; set; }

    public string Smena { get; set; }

    public int JezikNastaveId { get; set; }

    public bool DvojezicnoOdeljenje { get; set; }

    public int? PrviStraniJezikId { get; set; }

    public int UkupanBrojUcenika { get; set; }

    public int BrojUcenika { get; set; }

    public int BrojUcenica { get; set; }

    public DateTime DatumUnosa { get; set; }

    public DateTime? DatumIzmene { get; set; }

    public virtual Grade Grade { get; set; }

    public virtual Coodebookitem JezikNastave { get; set; }

    public virtual Coodebookitem PrviStraniJezik { get; set; }

    public virtual Coodebookitem VrstaOdeljenja { get; set; }
}