// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GradeManagementApp_Back.Models;

public partial class Codebook
{
    public int Id { get; set; }

    public string Naziv { get; set; }

    public DateTime DatumUnosa { get; set; }

    public DateTime? DatumIzmene { get; set; }

    public virtual ICollection<Codebookitem> Coodebookitems { get; set; } = new List<Codebookitem>();
}