// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GradeManagementApp_Back.Models;

public partial class Coodebookitem
{
    public int Id { get; set; }

    public string Naziv { get; set; }

    public int CoodebookId { get; set; }

    public DateTime DatumUnosa { get; set; }

    public DateTime? DatumIzmene { get; set; }

    public virtual ICollection<Class> ClassJezikNastaves { get; set; } = new List<Class>();

    public virtual ICollection<Class> ClassPrviStraniJeziks { get; set; } = new List<Class>();

    public virtual ICollection<Class> ClassVrstaOdeljenjas { get; set; } = new List<Class>();

    public virtual Codebook Coodebook { get; set; }

    public virtual ICollection<Grade> GradePrograms { get; set; } = new List<Grade>();

    public virtual ICollection<Grade> GradeRazreds { get; set; } = new List<Grade>();

    public virtual ICollection<Grade> GradeSkolskaGodinas { get; set; } = new List<Grade>();
}