// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GradeManagementApp_Back.Models;

public partial class Grade
{
    public int Id { get; set; }

    public int SkolskaGodinaId { get; set; }

    public int RazredId { get; set; }

    public int ProgramId { get; set; }

    public DateTime DatumUnosa { get; set; }

    public DateTime? DatumIzmene { get; set; }

    public virtual ICollection<Class> Classes { get; set; } = new List<Class>();

    public virtual Coodebookitem Program { get; set; }

    public virtual Coodebookitem Razred { get; set; }

    public virtual Coodebookitem SkolskaGodina { get; set; }
}