// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GradeManagementApp_Back.Models;

public partial class User
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string Lozinka { get; set; }
}